export { IFetchRestaurantData } from './fetch-restaurant-data.interface';
export { IRestaurantServiceFetchRestaurantsOfMerchantResponse as IUserServiceFetchRestaurantsOfMerchantResponse } from './restaurant-service-fetch-restaurants-of-merchant-response.interface';
export { IRestaurant } from './restaurant.interface';
export { IFetchRestaurantDetailData } from './fetch-restaurant-detail-data.interface';
export { IRestaurantServiceFetchRestaurantDetailOfMerchantResponse } from './restaurant-service-fetch-restaurant-detail-of-merchant-response.interface';
export { IOpenHour } from './open-hour.interface';
export { ICategory } from './category.interface';
export { IGetRestaurantStatisticData } from './get-restaurant-statistic-data.interface';
export { INumOrderAreaStatistic } from './num-order-area-statistic.interface';
export { IRestaurantStatistic } from './restaurant-statistic.interface';
export { IRestaurantStatisticResponse } from './get-restaurant-statistic-response.interface';
