export { IDeliveryServiceAcceptOrderResponse } from './delivery-service-accept-order-response.interface';
export { IOrderServicePickUpOrderResponse } from './order-service-pick-up-order-response.interface';
export { IOrderServiceCompleteOrderResponse } from './order-service-complete-order-response.interface';
export { IDriverResponse } from './driver-response.interface';
export { IDriver } from './driver.interface';
export { ILoginDriverData } from './login-customer/login-driver-data.interface';
export { IDriverData } from './register-driver/register-driver-data.interface';
export { ICreateDepositMoneyIntoMainAccountWalletResponse } from './create-deposit-money-into-main-account-wallet-response.interface';
export { ICreateDepositMoneyIntoMainAccountWalletData } from './create-deposit-money-into-main-account-wallet-data.interface';
