export { IAdmin } from './admin.interface';
export { IUserServiceFetchAdminResponse } from './user-service-fetch-admin-response.interface';
export { ILoginAdminData } from './login-admin-data.interface';
export { IVerifyRestaurantResponseData } from './verify-restaurant-response-data';
export { IFetchRestaurantData } from './fetch-restaurant-data.interface';
export { IRestaurantProfile } from './restaurant-profile.interface';
export { IUserServiceFetchRestaurantProfilesResponse } from './user-service-fetch-restaurant-profiles-response.interface';
export { IDriversResponse } from './drivers-response.interface';
export { IDriversData } from './drivers-data.interface';
